"""empty message

Revision ID: 3e27711ebd60
Revises: 53ee4ad09e19
Create Date: 2021-01-23 19:01:44.809381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e27711ebd60'
down_revision = '53ee4ad09e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reddit_post_title_key', 'reddit_post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reddit_post_title_key', 'reddit_post', ['title'])
    # ### end Alembic commands ###
