"""empty message

Revision ID: 53ee4ad09e19
Revises: d1e93364c47f
Create Date: 2021-01-23 18:44:56.329844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ee4ad09e19'
down_revision = 'd1e93364c47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_post',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('flair', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_post')
    # ### end Alembic commands ###
